
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-staff
owner: ucsb-cs156-f24
repo_name: team01-staff
pull_requests: [{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequestsTable","number":44,"title":"adding ent,repo,migfile","url":"https://github.com/ucsb-cs156-f24/team01-staff/pull/44"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-create-db-UCSBDiningCommonsMenuItem","number":43,"title":"Pc create db ucsb dining commons menu item","url":"https://github.com/ucsb-cs156-f24/team01-staff/pull/43"}]
