
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-staff
owner: ucsb-cs156-f24
repo_name: team01-staff
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-create-db-table-commits","number":56,"title":"pc - create database table for Commits","url":"https://github.com/ucsb-cs156-f24/team01-staff/pull/56"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-UCSB-DCMI-get-by-id","number":47,"title":"pc - add GET by id to UCSBDiningCommonsMenuItem controller","url":"https://github.com/ucsb-cs156-f24/team01-staff/pull/47"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-RecommendationRequestsTable","number":44,"title":"jp - Create database table, add GET (index) and POST (create), DELETE and PUT endpoint for RecommendationRequests","url":"https://github.com/ucsb-cs156-f24/team01-staff/pull/44"}]
